language: r
cache: packages
branches:
    only:
        - tomasokal-source
r_github_packages:
    - rstudio/blogdown

before_script:
    - Rscript -e 'blogdown::install_hugo()'

script:
    - Rscript -e 'blogdown::build_site()'
    
before_deploy:
    - cd $TRAVIS_BUILD_DIR

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_PAT
    on:
        branch: tomasokal-source
    local_dir: public
    target_branch: master